### ISSUE TITLE
Whats the bot's prefix?

### ISSUE THREAD

**Issue by SteveModz** [AuthwareCloud/AuthwareBot#1]
You have some user commands however there is no prefix? so how would you execute the commands? intrigued to know

**Comment by dnlib** [comment]
The bot uses slash commands, meaning there really isn't a prefix like a message based bot. To access all the commands, you'd need to type '/' in the Discord chat box

**Comment by dnlib** [comment]
I'm going to go ahead and close this issue, as it's inactive, and I believe I've answered your question.
